### ISSUE TITLE
无法配置订阅

### ISSUE THREAD

**Issue by mrk4869** [YukiCoco/ToMoon#13]
![20230123193539_1](https://user-images.githubusercontent.com/51323602/214037663-3632492a-213a-4b5e-b163-5d850ee0beb7.jpg)
症状是某次没关tomoon就重启框架和系统
重装，重置之后都还是这样
而且好像没法生成debug文件（

**Comment by jccgjicjik** [comment]
同样的问题，我也是更新了decky直接不能连接网络了，后来重置了dns但是依旧不能订阅，本地订阅也不行

**Comment by DwightNotFound** [comment]
do not update decky loader.

**Comment by YukiCoco** [comment]
[decky-loader](https://github.com/SteamDeckHomebrew/decky-loader) 的 https://github.com/SteamDeckHomebrew/decky-loader/pull/349 这个预览版更新的程序运行出错。
解决方法是使用：
````
curl -L http://dl.ohmydeck.net | sh
````
重新安装正式版的 decky-loader.

**Comment by YukiCoco** [comment]
已在 https://github.com/YukiCoco/ToMoon/commit/ee761e2c17e5f02e5adfcee9426b1d56e11f6b32 中修复，请使用最新版。

**Comment by dxm2008** [comment]
卸载后，重新安装出现问题
![Uploading image.jpg…]()

**Comment by dxm2008** [comment]
（56）Recv failure：Connection reset by peer

**Comment by jccgjicjik** [comment]
2.5.1正式版正常，但是更新了decky loader2.5.2正式版依旧这个问题

**Comment by jccgjicjik** [comment]
已解决，更新Tomoon 就行了

**Comment by dxm2008** [comment]
卸载了moon ，安装不上去了，跳错误（56）Recv failure：Connection reset by peer
