### ISSUE TITLE
If i need to change the deckos system proxy?

### ISSUE THREAD

**Issue by xzajyjs** [YukiCoco/ToMoon#18]

**Comment by xzajyjs** [comment]
Also, I can't change rule and global mode.

**Comment by xzajyjs** [comment]
If i do not change the deckos system proxy, it doesnot work. If i set the system proxy, when i turn off the TheMoon's proxy, i cannot connect to the network.

**Comment by YukiCoco** [comment]
默认开启了 Clash tun 模式，不需要修改 system proxy.
关于切换模式，请看：https://github.com/YukiCoco/ToMoon/issues/14#issuecomment-1437147891
