### ISSUE TITLE
Consider uploading to official decky store?

### ISSUE THREAD

**Issue by ParticleG** [YukiCoco/ToMoon#21]
It would be awsome if players could install this plugin from decky store directly, not by entering commands

**Comment by YukiCoco** [comment]
> Please be aware that we do not allow private repositories, "black-box" binaries, deliberately obfuscated code and any other items, processes etc that would undermine the team's ability to verify the functionality of the plugin and or any underlying software etc.

Due to Clash Premium is not an open-source Project, It is not allowed to submit it to decky's store.
