### ISSUE TITLE
控制面板Mode无法切换

### ISSUE THREAD

**Issue by tianyixin** [YukiCoco/ToMoon#24]
控制面板Mode无法切换, 应该是个类似下拉框的控件, 怎么点都弹不出来

**Comment by lsp199308** [comment]
重新装一次就行了

**Comment by YukiCoco** [comment]
这是一个 SteamOS 浏览器的显示问题，临时解决方法参考：
https://github.com/YukiCoco/ToMoon/issues/14#issuecomment-1437147891
