### ISSUE TITLE
steamdeck熄屏之后会自己断网，再打开tomoon就会卡住loading，reset network也不顶用，只能回桌面模式输指令恢复，希望以后的版本可以添加在游戏模式界面可以恢复dns的功能

### ISSUE THREAD

**Issue by Ceylan233** [YukiCoco/ToMoon#25]

**Comment by YukiCoco** [comment]
你使用的插件版本号是？

**Comment by Ceylan233** [comment]
0.1.4

**Comment by Ceylan233** [comment]
> 你使用的插件版本号是？

0.1.4

**Comment by Ceylan233** [comment]
> 你使用的插件版本号是？

0.1.4

**Comment by Ceylan233** [comment]
> 你使用的插件版本号是？

我尝试到桌面模式输入bash ~/tomoon_recover.sh，再回到游戏模式并没有恢复，貌似不是dns的问题，只要steamdeck使用tomoon中断网，就会卡住loading，重启才可以解决

**Comment by Ceylan233** [comment]
问题已得到解决，此问题是插件管理Decky的问题，测试平台为SteamOS稳定版本3.4.6，Decky为v2.6.4版本，将Decky设置中Decky Update Channel设置为Prerelease后，更新为v2.6.5-pre1即可解决这个问题

**Comment by Ceylan233** [comment]
问题已得到解决，此问题是插件管理Decky的问题，测试平台为SteamOS稳定版本3.4.6，Decky为v2.6.4版本，将Decky设置中Decky Update Channel设置为Prerelease后，更新为v2.6.5-pre1即可解决这个问题
