### ISSUE TITLE
挂了代理后下载会特别慢，分析应该是走的代理结点，可以默认配置一个域绕过下载以免偷跑流量吗？

### ISSUE THREAD

**Issue by kshq1996** [YukiCoco/ToMoon#27]
挂了代理后下载会特别慢，分析应该是走的代理结点，可以默认配置一个域绕过下载以免偷跑流量吗？

**Comment by micsama** [comment]
我也碰到这个问题,目前我的解决方案如下,希望能帮到你.
clash目前使用的配置文件如下(如果有不同可以根据自己的情况寻找):
/home/deck/homebrew/plugins/tomoon/bin/core/running_config.yaml
在后面rules加一条规则.注意缩进
```toml
- DOMAIN-SUFFIX, steamconnect.com, DIRECT
```
可能还有其他的需要添加的domain但是这应该暂时够了.
不过可能会因为更新订阅啥的被覆盖掉

**Comment by micsama** [comment]
不知道能否增加一个类似cfw的Parser的功能😂

**Comment by YukiCoco** [comment]
了解，下个版本会有跳过 Steam 下载代理的功能。

**Comment by YukiCoco** [comment]
> 我也碰到这个问题,目前我的解决方案如下,希望能帮到你.
> 
> **发现running_config修改没用,clash重新打开也会刷新掉,所以自己写一个本地toml了只能** ~clash目前使用的配置文件如下(如果有不同可以根据自己的情况寻找): /home/deck/homebrew/plugins/tomoon/bin/core/running_config.yaml~ 将自己的toml配置文件下载下来, 在后面rules加一条规则.注意缩进
> 
> ```toml
> - DOMAIN-SUFFIX, steamconcent.com, DIRECT
> ```
> 
> 然后用file:///path/to/your/toml 来导入.这样才能主动修改 ~不过可能会因为更新订阅啥的被覆盖掉~

先使用这个
````
- DOMAIN-SUFFIX, cm.steampowered.com, DIRECT
````

**Comment by YukiCoco** [comment]
在 https://github.com/YukiCoco/ToMoon/commit/ed210b5dc3c1604f8ff66ff765a2ef66c4573432 添加了跳过 Steam 下载功能。
