### ISSUE TITLE
steam os 稳定版无法显示插件

### ISSUE THREAD

**Issue by gangoogle** [YukiCoco/ToMoon#3]
通过deck里面输入url安装 以及 通过终端直接输入命令 ，甚至我直接把文件复制到了deck插件目录，通过deck商店安装的插件都是可以显示出来的。to moon无论如何都显示不出来。
而重装系统之前，我有两次成功安装to moon的经验。能否给点提示如何排查问题？

**Comment by gangoogle** [comment]
能否将deck的预览版本放置到onmydeck服务器已供选择，因为网络问题我无法下载deck原地址的预览版本。
您的项目非常好，我在贴吧里推荐了很多人，解决了很多人棘手的问题。请继续加油。很好的工作！来自中国的爱！

**Comment by YukiCoco** [comment]
请使用 Konsole 输入：
````
cd ~ && journalctl -b0  -u plugin_loader.service > backendlog.txt
````
然后将 `~/backendlog.txt` 这个文件贴上来

**Comment by YukiCoco** [comment]
使用这个脚本：
````shell
curl -L https://files.ohmydeck.net/fix.sh | sh
````

**Comment by gangoogle** [comment]
权限问题吗？

**Comment by gangoogle** [comment]
Dec 16 20:34:50 steamdeck systemd[1]: Started SteamDeck Plugin Loader.
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [selector_events][DEBUG]: Using selector: EpollSelector
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [loader][INFO]: plugin_path: /home/deck/homebrew/plugins
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [updater][INFO]: /home/deck/homebrew/services
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [updater][DEBUG]: current branch: 1
Dec 16 20:34:51 steamdeck PluginLoader[1109]: main.py:91: RuntimeWarning: coroutine 'chown_plugin_dir' was never awaited
Dec 16 20:34:51 steamdeck PluginLoader[1109]: RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [main][DEBUG]: Loading plugins
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [loader][INFO]: import plugins from /home/deck/homebrew/plugins
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [loader][INFO]: found plugin: tomoon
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [loader][INFO]: Loaded To Moon
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [loader][INFO]: found plugin: SDH-CssLoader
Dec 16 20:34:51 steamdeck PluginLoader[1137]: [selector_events][DEBUG]: Using selector: EpollSelector
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [loader][INFO]: Loaded CSS Loader
Dec 16 20:34:51 steamdeck PluginLoader[1138]: [selector_events][DEBUG]: Using selector: EpollSelector
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [inotify_buffer][DEBUG]: in-event <InotifyEvent: src_path=b'/home/deck/homebrew/plugins/tomoon', wd=1, mask=IN_ATTRIB|IN_ISDIR, cookie=0, name=tomoon>
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [inotify_buffer][DEBUG]: in-event <InotifyEvent: src_path=b'/home/deck/homebrew/plugins/tomoon', wd=2, mask=IN_ATTRIB|IN_ISDIR, cookie=0, name=>
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [inotify_buffer][DEBUG]: in-event <InotifyEvent: src_path=b'/home/deck/homebrew/plugins/tomoon/plugin.json', wd=2, mask=IN_ATTRIB, cookie=0, name=plugin.json>
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [inotify_buffer][DEBUG]: in-event <InotifyEvent: src_path=b'/home/deck/homebrew/plugins/tomoon/bin', wd=2, mask=IN_ATTRIB|IN_ISDIR, cookie=0, name=bin>
Dec 16 20:34:51 steamdeck PluginLoader[1142]: Starting back-end (tomoon v0.1.0)
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [inotify_buffer][DEBUG]: in-event <InotifyEvent: src_path=b'/home/deck/homebrew/plugins/tomoon/bin', wd=4, mask=IN_ATTRIB|IN_ISDIR, cookie=0, name=>
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [inotify_buffer][DEBUG]: in-event <InotifyEvent: src_path=b'/home/deck/homebrew/plugins/tomoon/bin/smartdns', wd=4, mask=IN_ATTRIB|IN_ISDIR, cookie=0, name=smartdns>
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [inotify_buffer][DEBUG]: in-event <InotifyEvent: src_path=b'/home/deck/homebrew/plugins/tomoon/bin/smartdns', wd=6, mask=IN_ATTRIB|IN_ISDIR, cookie=0, name=>
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [inotify_buffer][DEBUG]: in-event <InotifyEvent: src_path=b'/home/deck/homebrew/plugins/tomoon/bin/smartdns/smartdns', wd=6, mask=IN_ATTRIB, cookie=0, name=smartdns>
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [inotify_buffer][DEBUG]: in-event <InotifyEvent: src_path=b'/home/deck/homebrew/plugins/tomoon/bin/smartdns/gfw.conf', wd=6, mask=IN_ATTRIB, cookie=0, name=gfw.conf>
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [inotify_buffer][DEBUG]: in-event <InotifyEvent: src_path=b'/home/deck/homebrew/plugins/tomoon/bin/smartdns/config.conf', wd=6, mask=IN_ATTRIB, cookie=0, name=config.conf>
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [inotify_buffer][DEBUG]: in-event <InotifyEvent: src_path=b'/home/deck/homebrew/plugins/tomoon/bin/tomoon', wd=4, mask=IN_ATTRIB, cookie=0, name=tomoon>
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [inotify_buffer][DEBUG]: in-event <InotifyEvent: src_path=b'/home/deck/homebrew/plugins/tomoon/bin/core', wd=4, mask=IN_ATTRIB|IN_ISDIR, cookie=0, name=core>
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [inotify_buffer][DEBUG]: in-event <InotifyEvent: src_path=b'/home/deck/homebrew/plugins/tomoon/bin/core', wd=7, mask=IN_ATTRIB|IN_ISDIR, cookie=0, name=>
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [inotify_buffer][DEBUG]: in-event <InotifyEvent: src_path=b'/home/deck/homebrew/plugins/tomoon/bin/core/web', wd=7, mask=IN_ATTRIB|IN_ISDIR, cookie=0, name=web>
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [inotify_buffer][DEBUG]: in-event <InotifyEvent: src_path=b'/home/deck/homebrew/plugins/tomoon/bin/core/web', wd=8, mask=IN_ATTRIB|IN_ISDIR, cookie=0, name=>
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [injector][DEBUG]: Steam isn't available yet. Wait for a moment...
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [inotify_buffer][DEBUG]: in-event <InotifyEvent: src_path=b'/home/deck/homebrew/plugins/tomoon/bin/core/web/yacd-64.png', wd=8, mask=IN_ATTRIB, cookie=0, name=yacd-64.png>
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [inotify_buffer][DEBUG]: in-event <InotifyEvent: src_path=b'/home/deck/homebrew/plugins/tomoon/bin/core/web/manifest.webmanifest', wd=8, mask=IN_ATTRIB, cookie=0, name=manifest.webmanifest>
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [inotify_buffer][DEBUG]: in-event <InotifyEvent: src_path=b'/home/deck/homebrew/plugins/tomoon/bin/core/web/assets', wd=8, mask=IN_ATTRIB|IN_ISDIR, cookie=0, name=assets>
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [inotify_buffer][DEBUG]: in-event <InotifyEvent: src_path=b'/home/deck/homebrew/plugins/tomoon/bin/core/web/assets', wd=9, mask=IN_ATTRIB|IN_ISDIR, cookie=0, name=>
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [inotify_buffer][DEBUG]: in-event <InotifyEvent: src_path=b'/home/deck/homebrew/plugins/tomoon/bin/core/web/assets/Connections.1e70ab68.css', wd=9, mask=IN_ATTRIB, cookie=0, name=Connections.1e70ab68.css>
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [inotify_buffer][DEBUG]: in-event <InotifyEvent: src_path=b'/home/deck/homebrew/plugins/tomoon/bin/core/web/assets/Proxies.3fa3509d.css', wd=9, mask=IN_ATTRIB, cookie=0, name=Proxies.3fa3509d.css>
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [inotify_buffer][DEBUG]: in-event <InotifyEvent: src_path=b'/home/deck/homebrew/plugins/tomoon/bin/core/web/assets/Proxies.dc785aa4.js', wd=9, mask=IN_ATTRIB, cookie=0, name=Proxies.dc785aa4.js>
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [inotify_buffer][DEBUG]: in-event <InotifyEvent: src_path=b'/home/deck/homebrew/plugins/tomoon/bin/core/web/assets/Config.2829bffd.js', wd=9, mask=IN_ATTRIB, cookie=0, name=Config.2829bffd.js>
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [inotify_buffer][DEBUG]: in-event <InotifyEvent: src_path=b'/home/deck/homebrew/plugins/tomoon/bin/core/web/assets/TextFitler.b21c0577.css', wd=9, mask=IN_ATTRIB, cookie=0, name=TextFitler.b21c0577.css>
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [inotify_buffer][DEBUG]: in-event <InotifyEvent: src_path=b'/home/deck/homebrew/plugins/tomoon/bin/core/web/assets/TextFitler.5d7fa41d.js', wd=9, mask=IN_ATTRIB, cookie=0, name=TextFitler.5d7fa41d.js>
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [inotify_buffer][DEBUG]: in-event <InotifyEvent: src_path=b'/home/deck/homebrew/plugins/tomoon/bin/core/web/assets/logs.6e20f0cf.js', wd=9, mask=IN_ATTRIB, cookie=0, name=logs.6e20f0cf.js>
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [inotify_buffer][DEBUG]: in-event <InotifyEvent: src_path=b'/home/deck/homebrew/plugins/tomoon/bin/core/web/assets/Rules.a5a3995b.js', wd=9, mask=IN_ATTRIB, cookie=0, name=Rules.a5a3995b.js>
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [inotify_buffer][DEBUG]: in-event <InotifyEvent: src_path=b'/home/deck/homebrew/plugins/tomoon/bin/core/web/assets/zh.9b79b7bf.js', wd=9, mask=IN_ATTRIB, cookie=0, name=zh.9b79b7bf.js>
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [inotify_buffer][DEBUG]: in-event <InotifyEvent: src_path=b'/home/deck/homebrew/plugins/tomoon/bin/core/web/assets/Select.1e55eba1.css', wd=9, mask=IN_ATTRIB, cookie=0, name=Select.1e55eba1.css>
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [inotify_buffer][DEBUG]: in-event <InotifyEvent: src_path=b'/home/deck/homebrew/plugins/tomoon/bin/core/web/assets/index.b38debfc.css', wd=9, mask=IN_ATTRIB, cookie=0, name=index.b38debfc.css>
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [inotify_buffer][DEBUG]: in-event <InotifyEvent: src_path=b'/home/deck/homebrew/plugins/tomoon/bin/core/web/assets/inter-latin-800-normal.a51ac27d.woff2', wd=9, mask=IN_ATTRIB, cookie=0, name=inter-latin-800-normal.a51ac27d.woff2>
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [inotify_buffer][DEBUG]: in-event <InotifyEvent: src_path=b'/home/deck/homebrew/plugins/tomoon/bin/core/web/assets/roboto-mono-latin-400-normal.7295944e.woff2', wd=9, mask=IN_ATTRIB, cookie=0, name=roboto-mono-latin-400-normal.7295944e.woff2>
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [inotify_buffer][DEBUG]: in-event <InotifyEvent: src_path=b'/home/deck/homebrew/plugins/tomoon/bin/core/web/assets/Connections.6fed35ec.js', wd=9, mask=IN_ATTRIB, cookie=0, name=Connections.6fed35ec.js>
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [inotify_buffer][DEBUG]: in-event <InotifyEvent: src_path=b'/home/deck/homebrew/plugins/tomoon/bin/core/web/assets/chevron-down.d92c210e.js', wd=9, mask=IN_ATTRIB, cookie=0, name=chevron-down.d92c210e.js>
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [inotify_buffer][DEBUG]: in-event <InotifyEvent: src_path=b'/home/deck/homebrew/plugins/tomoon/bin/core/web/assets/index.1428ab75.js', wd=9, mask=IN_ATTRIB, cookie=0, name=index.1428ab75.js>
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [inotify_buffer][DEBUG]: in-event <InotifyEvent: src_path=b'/home/deck/homebrew/plugins/tomoon/bin/core/web/assets/inter-latin-800-normal.d08d7178.woff', wd=9, mask=IN_ATTRIB, cookie=0, name=inter-latin-800-normal.d08d7178.woff>
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [inotify_buffer][DEBUG]: in-event <InotifyEvent: src_path=b'/home/deck/homebrew/plugins/tomoon/bin/core/web/assets/index.4bcef007.js', wd=9, mask=IN_ATTRIB, cookie=0, name=index.4bcef007.js>
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [inotify_buffer][DEBUG]: in-event <InotifyEvent: src_path=b'/home/deck/homebrew/plugins/tomoon/bin/core/web/assets/Rules.e03c54a8.css', wd=9, mask=IN_ATTRIB, cookie=0, name=Rules.e03c54a8.css>
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [inotify_buffer][DEBUG]: in-event <InotifyEvent: src_path=b'/home/deck/homebrew/plugins/tomoon/bin/core/web/assets/Logs.4b8e75d1.css', wd=9, mask=IN_ATTRIB, cookie=0, name=Logs.4b8e75d1.css>
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [inotify_buffer][DEBUG]: in-event <InotifyEvent: src_path=b'/home/deck/homebrew/plugins/tomoon/bin/core/web/assets/Logs.0b6fcee1.js', wd=9, mask=IN_ATTRIB, cookie=0, name=Logs.0b6fcee1.js>
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [inotify_buffer][DEBUG]: in-event <InotifyEvent: src_path=b'/home/deck/homebrew/plugins/tomoon/bin/core/web/assets/Select.bdd10c8a.js', wd=9, mask=IN_ATTRIB, cookie=0, name=Select.bdd10c8a.js>
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [inotify_buffer][DEBUG]: in-event <InotifyEvent: src_path=b'/home/deck/homebrew/plugins/tomoon/bin/core/web/assets/Config.7bc73fad.css', wd=9, mask=IN_ATTRIB, cookie=0, name=Config.7bc73fad.css>
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [inotify_buffer][DEBUG]: in-event <InotifyEvent: src_path=b'/home/deck/homebrew/plugins/tomoon/bin/core/web/assets/Fab.4f6fab8b.js', wd=9, mask=IN_ATTRIB, cookie=0, name=Fab.4f6fab8b.js>
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [inotify_buffer][DEBUG]: in-event <InotifyEvent: src_path=b'/home/deck/homebrew/plugins/tomoon/bin/core/web/assets/play.59a01dbd.js', wd=9, mask=IN_ATTRIB, cookie=0, name=play.59a01dbd.js>
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [inotify_buffer][DEBUG]: in-event <InotifyEvent: src_path=b'/home/deck/homebrew/plugins/tomoon/bin/core/web/assets/en.fb34eaf7.js', wd=9, mask=IN_ATTRIB, cookie=0, name=en.fb34eaf7.js>
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [inotify_buffer][DEBUG]: in-event <InotifyEvent: src_path=b'/home/deck/homebrew/plugins/tomoon/bin/core/web/assets/index.47b45d26.js', wd=9, mask=IN_ATTRIB, cookie=0, name=index.47b45d26.js>
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [inotify_buffer][DEBUG]: in-event <InotifyEvent: src_path=b'/home/deck/homebrew/plugins/tomoon/bin/core/web/assets/index.esm.7b716043.js', wd=9, mask=IN_ATTRIB, cookie=0, name=index.esm.7b716043.js>
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [inotify_buffer][DEBUG]: in-event <InotifyEvent: src_path=b'/home/deck/homebrew/plugins/tomoon/bin/core/web/assets/debounce.c2d20996.js', wd=9, mask=IN_ATTRIB, cookie=0, name=debounce.c2d20996.js>
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [inotify_buffer][DEBUG]: in-event <InotifyEvent: src_path=b'/home/deck/homebrew/plugins/tomoon/bin/core/web/assets/roboto-mono-latin-400-normal.dffdffa7.woff', wd=9, mask=IN_ATTRIB, cookie=0, name=roboto-mono-latin-400-normal.dffdffa7.woff>
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [inotify_buffer][DEBUG]: in-event <InotifyEvent: src_path=b'/home/deck/homebrew/plugins/tomoon/bin/core/web/assets/chart-lib.a8ad03fd.js', wd=9, mask=IN_ATTRIB, cookie=0, name=chart-lib.a8ad03fd.js>
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [inotify_buffer][DEBUG]: in-event <InotifyEvent: src_path=b'/home/deck/homebrew/plugins/tomoon/bin/core/web/assets/inter-latin-400-normal.3ea830d4.woff', wd=9, mask=IN_ATTRIB, cookie=0, name=inter-latin-400-normal.3ea830d4.woff>
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [inotify_buffer][DEBUG]: in-event <InotifyEvent: src_path=b'/home/deck/homebrew/plugins/tomoon/bin/core/web/assets/Fab.a0a7e573.css', wd=9, mask=IN_ATTRIB, cookie=0, name=Fab.a0a7e573.css>
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [inotify_buffer][DEBUG]: in-event <InotifyEvent: src_path=b'/home/deck/homebrew/plugins/tomoon/bin/core/web/assets/inter-latin-400-normal.0364d368.woff2', wd=9, mask=IN_ATTRIB, cookie=0, name=inter-latin-400-normal.0364d368.woff2>
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [inotify_buffer][DEBUG]: in-event <InotifyEvent: src_path=b'/home/deck/homebrew/plugins/tomoon/bin/core/web/assets/useRemainingViewPortHeight.2e9a6590.js', wd=9, mask=IN_ATTRIB, cookie=0, name=useRemainingViewPortHeight.2e9a6590.js>
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [inotify_buffer][DEBUG]: in-event <InotifyEvent: src_path=b'/home/deck/homebrew/plugins/tomoon/bin/core/web/index.html', wd=8, mask=IN_ATTRIB, cookie=0, name=index.html>
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [inotify_buffer][DEBUG]: in-event <InotifyEvent: src_path=b'/home/deck/homebrew/plugins/tomoon/bin/core/web/apple-touch-icon-precomposed.png', wd=8, mask=IN_ATTRIB, cookie=0, name=apple-touch-icon-precomposed.png>
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [inotify_buffer][DEBUG]: in-event <InotifyEvent: src_path=b'/home/deck/homebrew/plugins/tomoon/bin/core/web/CNAME', wd=8, mask=IN_ATTRIB, cookie=0, name=CNAME>
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [inotify_buffer][DEBUG]: in-event <InotifyEvent: src_path=b'/home/deck/homebrew/plugins/tomoon/bin/core/web/registerSW.js', wd=8, mask=IN_ATTRIB, cookie=0, name=registerSW.js>
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [inotify_buffer][DEBUG]: in-event <InotifyEvent: src_path=b'/home/deck/homebrew/plugins/tomoon/bin/core/web/yacd.ico', wd=8, mask=IN_ATTRIB, cookie=0, name=yacd.ico>
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [inotify_buffer][DEBUG]: in-event <InotifyEvent: src_path=b'/home/deck/homebrew/plugins/tomoon/bin/core/web/sw.js', wd=8, mask=IN_ATTRIB, cookie=0, name=sw.js>
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [inotify_buffer][DEBUG]: in-event <InotifyEvent: src_path=b'/home/deck/homebrew/plugins/tomoon/bin/core/web/_headers', wd=8, mask=IN_ATTRIB, cookie=0, name=_headers>
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [inotify_buffer][DEBUG]: in-event <InotifyEvent: src_path=b'/home/deck/homebrew/plugins/tomoon/bin/core/web/yacd-128.png', wd=8, mask=IN_ATTRIB, cookie=0, name=yacd-128.png>
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [inotify_buffer][DEBUG]: in-event <InotifyEvent: src_path=b'/home/deck/homebrew/plugins/tomoon/bin/core/Country.mmdb', wd=7, mask=IN_ATTRIB, cookie=0, name=Country.mmdb>
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [inotify_buffer][DEBUG]: in-event <InotifyEvent: src_path=b'/home/deck/homebrew/plugins/tomoon/bin/core/clash', wd=7, mask=IN_ATTRIB, cookie=0, name=clash>
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [inotify_buffer][DEBUG]: in-event <InotifyEvent: src_path=b'/home/deck/homebrew/plugins/tomoon/dist', wd=2, mask=IN_ATTRIB|IN_ISDIR, cookie=0, name=dist>
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [inotify_buffer][DEBUG]: in-event <InotifyEvent: src_path=b'/home/deck/homebrew/plugins/tomoon/dist', wd=5, mask=IN_ATTRIB|IN_ISDIR, cookie=0, name=>
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [inotify_buffer][DEBUG]: in-event <InotifyEvent: src_path=b'/home/deck/homebrew/plugins/tomoon/dist/index.js', wd=5, mask=IN_ATTRIB, cookie=0, name=index.js>
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [inotify_buffer][DEBUG]: in-event <InotifyEvent: src_path=b'/home/deck/homebrew/plugins/tomoon/main.py', wd=2, mask=IN_ATTRIB, cookie=0, name=main.py>
Dec 16 20:34:51 steamdeck PluginLoader[1138]: [css_utils][INFO]: [CSS_Loader] Waiting 1s...
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [loader][DEBUG]: file modified: /home/deck/homebrew/plugins/tomoon/dist/index.js
Dec 16 20:34:51 steamdeck PluginLoader[1109]: [loader][DEBUG]: file modified: /home/deck/homebrew/plugins/tomoon/main.py
Dec 16 20:34:52 steamdeck PluginLoader[1138]: [css_utils][INFO]: [CSS_Loader] Initializing css loader...
Dec 16 20:34:52 steamdeck PluginLoader[1138]: [css_utils][INFO]: [CSS_Loader] Max supported manifest version: 4
Dec 16 20:34:52 steamdeck PluginLoader[1138]: [css_utils][INFO]: [CSS_Loader] Loading themedb https://github.com/suchmememanyskill/CssLoader-ThemeDb/releases/download/1.1.0/themes.json
Dec 16 20:34:56 steamdeck PluginLoader[1109]: [main][DEBUG]: Couldn't find GamepadUI tab, waiting...
Dec 16 20:35:01 steamdeck PluginLoader[1109]: [loader][INFO]: Hot reload enabled
Dec 16 20:35:01 steamdeck PluginLoader[1109]: [main][INFO]: Loading Decky frontend!
Dec 16 20:35:01 steamdeck PluginLoader[1109]: [main][DEBUG]: Page event: None
Dec 16 20:35:01 steamdeck PluginLoader[1109]: [main][DEBUG]: Page event: None
Dec 16 20:35:05 steamdeck PluginLoader[1109]: [main][DEBUG]: Page event: Page.windowOpen
Dec 16 20:35:07 steamdeck PluginLoader[1109]: [web_protocol][ERROR]: Error handling request
Dec 16 20:35:07 steamdeck PluginLoader[1109]: Traceback (most recent call last):
Dec 16 20:35:07 steamdeck PluginLoader[1109]:   File "aiohttp/web_protocol.py", line 435, in _handle_request
Dec 16 20:35:07 steamdeck PluginLoader[1109]:   File "aiohttp/web_app.py", line 504, in _handle
Dec 16 20:35:07 steamdeck PluginLoader[1109]:   File "aiohttp/web_middlewares.py", line 117, in impl
Dec 16 20:35:07 steamdeck PluginLoader[1109]:   File "helpers.py", line 37, in csrf_middleware
Dec 16 20:35:07 steamdeck PluginLoader[1109]:   File "aiohttp/web_urldispatcher.py", line 195, in handler_wrapper
Dec 16 20:35:07 steamdeck PluginLoader[1109]:   File "loader.py", line 122, in handle_frontend_bundle
Dec 16 20:35:07 steamdeck PluginLoader[1109]:   File "encodings/ascii.py", line 26, in decode
Dec 16 20:35:07 steamdeck PluginLoader[1109]: UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 159978: ordinal not in range(128)
Dec 16 20:35:07 steamdeck PluginLoader[1109]: [web_protocol][ERROR]: Error handling request
Dec 16 20:35:07 steamdeck PluginLoader[1109]: Traceback (most recent call last):
Dec 16 20:35:07 steamdeck PluginLoader[1109]:   File "aiohttp/web_protocol.py", line 435, in _handle_request
Dec 16 20:35:07 steamdeck PluginLoader[1109]:   File "aiohttp/web_app.py", line 504, in _handle
Dec 16 20:35:07 steamdeck PluginLoader[1109]:   File "aiohttp/web_middlewares.py", line 117, in impl
Dec 16 20:35:07 steamdeck PluginLoader[1109]:   File "helpers.py", line 37, in csrf_middleware
Dec 16 20:35:07 steamdeck PluginLoader[1109]:   File "aiohttp/web_urldispatcher.py", line 195, in handler_wrapper
Dec 16 20:35:07 steamdeck PluginLoader[1109]:   File "loader.py", line 122, in handle_frontend_bundle
Dec 16 20:35:07 steamdeck PluginLoader[1109]:   File "encodings/ascii.py", line 26, in decode
Dec 16 20:35:07 steamdeck PluginLoader[1109]: UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 75706: ordinal not in range(128)
Dec 16 20:35:10 steamdeck PluginLoader[1109]: [main][DEBUG]: Page event: Page.frameAttached
Dec 16 20:35:10 steamdeck PluginLoader[1109]: [main][DEBUG]: Page event: Page.frameStartedLoading
Dec 16 20:35:11 steamdeck PluginLoader[1109]: [main][DEBUG]: Page event: Page.frameNavigated
Dec 16 20:35:12 steamdeck PluginLoader[1109]: [main][DEBUG]: Page event: Page.frameStoppedLoading
Dec 16 20:35:21 steamdeck PluginLoader[1109]: [updater][DEBUG]: checking for updates
Dec 16 20:35:21 steamdeck PluginLoader[1109]: [updater][DEBUG]: current branch: 1
Dec 16 20:35:22 steamdeck PluginLoader[1109]: [updater][DEBUG]: determining release type to find, branch is 1
Dec 16 20:35:22 steamdeck PluginLoader[1109]: [updater][DEBUG]: release type: pre-release
Dec 16 20:35:22 steamdeck PluginLoader[1109]: [updater][INFO]: Updated remote version information
