### ISSUE TITLE
在steamos更新3.4.8稳定版之后，tomoon无法正常加载使用。

### ISSUE THREAD

**Issue by RAVENSFD** [YukiCoco/ToMoon#33]
如题，请问该如何解决
![IMG_20230615_120442](https://github.com/YukiCoco/ToMoon/assets/91169625/f0e2979a-0eb6-4b50-a204-e08f6790b678)

**Comment by YukiCoco** [comment]
更新 tomoon 到最新版本

**Comment by RAVENSFD** [comment]
在启动时提示Failed to start,please check tmp/tomoon.log
[tomoon.log](https://github.com/YukiCoco/ToMoon/files/11756366/tomoon.log)

**Comment by YukiCoco** [comment]
> 在启动时提示Failed to start,please check tmp/tomoon.log [tomoon.log](https://github.com/YukiCoco/ToMoon/files/11756366/tomoon.log)

````
10:25:22 [ERROR] run Clash failed: Permission denied (os error 13)
````
执行：
````
sudo chmod a+x /home/deck/homebrew/plugins/tomoon/bin/core/clash
````
看看

**Comment by RAVENSFD** [comment]
谢谢，问题已解决！
