### ISSUE TITLE
dl.ohmydeck.net and moon.ohmydeck.net are down

### ISSUE THREAD

**Issue by criphc** [YukiCoco/ToMoon#34]
Both dl.ohmydeck.net and moon.ohmydeck.net are down, reporting: 
> **Error 403 - This web app is stopped.**
> 
> The web app you have attempted to reach is currently stopped and does not accept any requests. Please try to reload the page or visit it again soon.
> 
> If you are the web app administrator, please find the common 403 error scenarios and resolution [here](https://go.microsoft.com/fwlink/?linkid=2095007). For further troubleshooting tools and recommendations, please visit [Azure Portal](https://portal.azure.com/).

Causing both the installation of Plugin Loader and ToMoon to fail.

**Comment by YukiCoco** [comment]
fixed.
