### ISSUE TITLE
未正确关闭ToMoon之后，Decky Loader无法正确加载

### ISSUE THREAD

**Issue by scyq** [YukiCoco/ToMoon#4]
未正确关闭ToMoon不可以上网，通过Shell脚本修复之后可以上网
但Steam OS下Decky Loader无法正确加载，重新开关开发者模式也没用

**Comment by YukiCoco** [comment]
https://github.com/YukiCoco/ToMoon/commit/71812ef3cca77c465c440dfcf83fcbc2eaa20853 已修复
