### ISSUE TITLE
clash内核版本问题

### ISSUE THREAD

**Issue by wozaiha** [YukiCoco/ToMoon#42]
目前使用的内核为Clash 2023.05.29
在之前的release中曾提到换用了ClashMeta内核，请问为何又换回来了？

**Comment by Karen-lai** [comment]
希望希望作者能够更换仍在更新的Meta内核，谢谢！

**Comment by Karen-lai** [comment]
应该是dns解析的问题，用ip作为入口的节点能够正常连接。

**Comment by wozaiha** [comment]
使用[clash.meta-linux-amd64-cgo-v1.16.0](https://github.com/MetaCubeX/mihomo/releases/download/v1.16.0/clash.meta-linux-amd64-cgo-v1.16.0.gz)替换后开启tomoon会导致全局无法上网。
另：不替换的情况下，保持Tomoon启动时，每次休眠后都会无法连接Steam服务器，需要手动关闭并重新开启才能成功连上。

**Comment by YukiCoco** [comment]
现已切换到 Mihomo https://github.com/YukiCoco/ToMoon/pull/63
