### ISSUE TITLE
启动失败，报请查看tmp/tomoon.log

### ISSUE THREAD

**Issue by antinomypa** [YukiCoco/ToMoon#44]
[tomoon.debug.log](https://github.com/YukiCoco/ToMoon/files/13796975/tomoon.debug.log)
附件为生成的debug log
我唯一看到的ERROR log只有：
03:12:48 [INFO] set clash status to true
03:12:48 [ERROR] Run clash error: Error Kind: ConfigFormatError, Error Message: No such file or directory (os error 2))
03:12:48 [INFO] Got USDPL call 19 (`get_clash_status`, params: 0)

**Comment by GingerWine** [comment]
@antinomypa 请问是如何解决的呢

**Comment by antinomypa** [comment]
> [@antinomypa](https://github.com/antinomypa) 请问是如何解决的呢

重新订阅一下后好了
