### ISSUE TITLE
打开Skip Steam Proxy之后，Steam下载有时候还是走代理

### ISSUE THREAD

**Issue by ayssia** [YukiCoco/ToMoon#45]
结果流量很快就耗光了……

**Comment by murasaki-nin** [comment]
我看这个选项的说明是 「Enable for direct Steam downloads」，会不会关掉它才不走代理

**Comment by YukiCoco** [comment]
如果打开 Skip Steam Proxy 后下载服务器仍然走代理，请重启你的机器。 https://github.com/YukiCoco/ToMoon/pull/61
