### ISSUE TITLE
在2024/02/28的Steam客户端更新已后无法打开dashboard

### ISSUE THREAD

**Issue by LittleFIve233** [YukiCoco/ToMoon#49]
tomoon版本：0.1.6
SteamOS：3.5.7，3.5.14

Steam在2月28日推送了客户端更新
https://store.steampowered.com/news/collection/steam/?emclan=103582791470414830&emgid=4157455695153534562

https://github.com/YukiCoco/ToMoon/issues/46
与此问题如出一辙

**Comment by YukiCoco** [comment]
作者设备坏了😂，需要一段时间来修复这个问题

**Comment by LittleFIve233** [comment]
> 作者设备坏了😂，需要一段时间来修复这个问题

草
