### ISSUE TITLE
"download error" when downloading subscription

### ISSUE THREAD

**Issue by David1016** [YukiCoco/ToMoon#5]
"download error" when downloading subscription

**Comment by David1016** [comment]
sorry it is "download failed" actually

**Comment by HCui91** [comment]
Got 500 error when posting to X:55556/download_sub. Response message was `invalid peer certificate contents: invalid peer certificate: UnknownIssuer`

**Comment by HCui91** [comment]
Probably due to a different set of built-in cert in the OS. 
Problem solved if downloading from the desktop mode Firefox with trusting the insecure connection. 
It is strange since the subconverter URL (I used sub.id9.cc) did not show insecure at least on macOS/Windows Chrome.

**Comment by ahhxyz** [comment]
I have the same issue

**Comment by ahhxyz** [comment]
always "download error"

**Comment by YukiCoco** [comment]
确定你到订阅地址没有被墙。
________________________________

**Comment by ahhxyz** [comment]
@YukiCoco 找到问题了，我使用了代理服务商提供的windows客户端的订阅地址，才导致这个错误。改成linux客户端的订阅地址，就好了。

**Comment by wjy12394** [comment]
> @YukiCoco 找到问题了，我使用了代理服务商提供的windows客户端的订阅地址，才导致这个错误。改成linux客户端的订阅地址，就好了。

感谢，找了好久终于找到答案了！
