### ISSUE TITLE
是否可以切换核心为Clash Meta (mihomo)

### ISSUE THREAD

**Issue by mzdluo123** [YukiCoco/ToMoon#52]
mihomo提供了更多的协议支持，并且处于活跃开发中

https://github.com/MetaCubeX/mihomo/releases

https://wiki.metacubex.one/config/

**Comment by YukiCoco** [comment]
暂无更新计划，如有需要请手动替换内核文件

~/homebrew/plugins/tomoon/bin/core/clash

**Comment by YukiCoco** [comment]
https://github.com/YukiCoco/ToMoon/pull/63
