### ISSUE TITLE
dashboard打不开

### ISSUE THREAD

**Issue by SickoZ3b3** [YukiCoco/ToMoon#55]
tomoon版本0.1.6
系统3.5.17
dashboard和里面任何浏览器相关的都打不开

同时想问问怎么更新这个插件？

**Comment by YukiCoco** [comment]
再次运行安装脚本即可更新插件

**Comment by SickoZ3b3** [comment]
> 再次运行安装脚本即可更新插件

更新后问题解决 谢谢
