### ISSUE TITLE
游戏中突然断网后，tomoon貌似会占用大量cpu

### ISSUE THREAD

**Issue by lance6716** [YukiCoco/ToMoon#57]
如果启用了tomoon的clash，在每次WiFi意外断开时风扇就会狂转、帧率剧烈下降。马上把clash关了就会好。怀疑有一些busy loop

**Comment by ayssia** [comment]
同样有类似情况，具体来说，在家里连着wifi的时候休眠，然后带到外面开机（无网络）也会有这种现象，关闭clash开关才能恢复。

**Comment by lance6716** [comment]
https://nga.178.com/read.php?tid=39701145&_fp=3

nga 也看到了这个问题

**Comment by ayssia** [comment]
不知是否是错觉，这一现象已经随着 https://github.com/YukiCoco/ToMoon/pull/63 （或后续更新）消失了，也许已经解决？并不确定。
