### ISSUE TITLE
使用新版家庭共享版本Steam后失效无法启用

### ISSUE THREAD

**Issue by DongLinghe** [YukiCoco/ToMoon#58]
TypeError：Cannot read properties of undefined （reading “title"）
at eval…
![image](https://github.com/YukiCoco/ToMoon/assets/53119341/cb311bb1-a5cc-4642-a8cc-60048798e86d)

**Comment by tomcatzh** [comment]
+1，整个UI改了，不少插件都失效了

**Comment by YukiCoco** [comment]
新的 pr https://github.com/YukiCoco/ToMoon/commit/2b378c1274d5436082f59162d4948571de223ebf 修复了这个问题，可以更新看看
