### ISSUE TITLE
Telegram群组验证死活过不去，验证网页显示「初始化失败」(附截图)

### ISSUE THREAD

**Issue by RTX10086** [YukiCoco/ToMoon#6]
<img width="690" alt="image" src="https://user-images.githubusercontent.com/46842736/210138767-c13e3e60-c1a6-4c3f-8066-a9685ac858bb.png">

所有权限都给了，纯净Safari浏览器、Chrome浏览器（无任何插件、扩展」都尝试了，都不行。

**Comment by YukiCoco** [comment]
你加入的时候验证机器人有问题。
