### ISSUE TITLE
[bug] 插件无法安装

### ISSUE THREAD

**Issue by JamesW99** [YukiCoco/ToMoon#65]
更新的时候错误的使用了这个代码：curl -L http://dl.ohmydeck.net/ | sh

反复重装，重启，插件都没有再出现。

**Comment by YukiCoco** [comment]
有没有更详细的日志？比如执行命令之后的输出

**Comment by JamesW99** [comment]
重装的时候终端显示安装成功。没有任何错误提示。

还尝试了这个命令卸载，卸载后重装依然没有显示。
curl -L https://github.com/SteamDeckHomebrew/decky-installer/releases/latest/download/uninstall.sh | sh

哪里可以看到日志？

**Comment by YukiCoco** [comment]
尝试使用官方的步骤安装 decky loader 看看：
https://github.com/SteamDeckHomebrew/decky-loader

**Comment by YukiCoco** [comment]
是 Loader 镜像的问题，现在可以再次执行安装命令尝试安装

**Comment by kimiko116** [comment]
现在我用国内源安装的在游戏模式中不显示，在github源安装的显示但是全部插件都要从新装。推测是plugins个这文件夹国内源在/home/deck/homebrew/但是github源在/home/deck/。试着将tomoon文件夹移到/home/deck/plugins能在decky loader显示但是报错。日志看不懂，来回就是
02:20:25 [ERROR] SettingsJson.save(/home/deck/.config/tomoon/tomoon.json) error: Permission denied (os error 13)或
02:33:02 [ERROR] Run clash error: Error Kind: ConfigFormatError, Error Message: No such file or directory (os error 2))
[tomoon.log](https://github.com/YukiCoco/ToMoon/files/15132006/tomoon.log)

试着卸载github源重新安装国内源还是不在游戏模式中显示

**Comment by JamesW99** [comment]
> 是 Loader 镜像的问题，现在可以再次执行安装命令尝试安装

已解决，感谢
