### ISSUE TITLE
关于dns修改位置的建议

### ISSUE THREAD

**Issue by VisoTC** [YukiCoco/ToMoon#7]
steam deck 的 dns 代理并不是 NetworkManager 最终控制的，他的上游是 systemd-resolve，所以建议dns修改位置改为 /etc/systemd/resolved.conf 设置 DNS= 为 clash 地址，FallbackDNS= 为 1.1.1.1 等外部 dns，这样 clash 如果被退出的话 systemd-resolve 会自动 Fallback 到外部DNS。如果担心dns缓存导致tun需要一点时间反应可以在clash启动的时候执行 `sudo sudo systemd-resolve --flush-caches` 去刷新dns缓存

**Comment by YukiCoco** [comment]
在较低的 SteamOS 版本（比如 3.1） systemd-resolve 并不是默认启动的，这也是为什么修改 NetworkManager 的原因。
现在您提出的修改 systemd-resolve 是一个好方法，会在后面的更新使用的。

**Comment by YukiCoco** [comment]
已在 https://github.com/YukiCoco/ToMoon/commit/71812ef3cca77c465c440dfcf83fcbc2eaa20853 添加此功能。
