### ISSUE TITLE
无限下载节点配置

### ISSUE THREAD

**Issue by zaprtqa** [YukiCoco/ToMoon#73]
在同一个局域网，手机扫了，节点下载无限转圈圈，电脑可以很快的下载好

**Comment by zaprtqa** [comment]
tomoon版本0.2.4

**Comment by zaprtqa** [comment]
无法导入节点

**Comment by tongzhimenhao** [comment]
扫描是导入不了了，建议用用主页下面说的file:///....来手动导入yaml文件，麻烦是麻烦了一些，

**Comment by YukiCoco** [comment]
已在 https://github.com/YukiCoco/ToMoon/releases/tag/v0.2.5 修复
