### ISSUE TITLE
无法打开Dashboard

### ISSUE THREAD

**Issue by cnqdztp** [YukiCoco/ToMoon#74]
版本0.24
无法正常连接到dashboard
![20240528224353_1](https://github.com/YukiCoco/ToMoon/assets/77837887/c42601d0-64ab-4ebe-89d7-401c955be39a)
![20240528224340_1](https://github.com/YukiCoco/ToMoon/assets/77837887/08fb028d-58c3-47a6-a603-923928f24859)

**Comment by YukiCoco** [comment]
你的订阅里面带密码，需要填进去才行

**Comment by cnqdztp** [comment]
感谢！
