### ISSUE TITLE
桌面模式可能是dns污染，重置命令无效

### ISSUE THREAD

**Issue by mgserss** [YukiCoco/ToMoon#8]
一开始在os模式开插件，然后去桌面模式都能正常访问，在关机前忘记回去关闭插件，后面再重启后，os系统一切正常，但是桌面模式默认浏览器访问不了网站，discover商店能访问但下载不了应用，桌面的steam一直离线登陆不了，按照教程重置dns后重启也不行，希望能解决这个问题。

**Comment by YukiCoco** [comment]
使用 `cat /etc/resolv.conf` 看看 DNS 的配置

**Comment by mgserss** [comment]
> 使用 `cat /etc/resolv.conf` 看看 DNS 的配置

/etc/resolv.conf
`# Generated by NetworkManager`
`nameserver 192.168.31.1`

只有这一段

**Comment by YukiCoco** [comment]
> 

不是 DNS 的问题，可能是你安装了什么软件设置了桌面模式的代理。
